{% set name = "ndarray-listener" %}
{% set version = "2.0.0" %}
{% set sha256 = "2993f72b084721f0b65818b42b5374235d9cfca0d87e4c4785a27b628f5f2080" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/ndarray_listener/ndarray_listener-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools >=38.4.0
    - pytest-runner
  run:
    - python
    - numpy >=1.12

test:
  requires:
    - pytest >=3
    - pytest-pep8
  imports:
    - ndarray_listener
  commands:
    - python -c "import sys; import ndarray_listener; sys.exit(ndarray_listener.test())"

about:
  home: https://github.com/limix/ndarray-listener
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Implementation of the Observer pattern for NumPy arrays.'
  doc_url: https://github.com/limix/ndarray-listener
  dev_url: https://github.com/limix/ndarray-listener

extra:
  recipe-maintainers:
    - Horta
