{% set name = "ndarray-listener" %}
{% set version = "1.0.23" %}
{% set sha256 = "aa5d884aa7fa2965853bce9d6f866bdbc1007c5e231967f43f53f92fa7d66540" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - numpy >=1.10

test:
  requires:
    - pytest >=3
    - pytest-pep8
  imports:
    - ndarray_listener
  commands:
    - python -c "import sys; import ndarray_listener; sys.exit(ndarray_listener.test())"

about:
  home: https://github.com/limix/ndarray-listener
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Implementation of the Observer pattern for NumPy arrays.'
  doc_url: https://github.com/limix/ndarray-listener
  dev_url: https://github.com/limix/ndarray-listener

extra:
  recipe-maintainers:
    - Horta
