travis:
  secure:
    BINSTAR_TOKEN: lsvYkTaIfvu2VplMAgqY2K/bwQ8pJhC9KUVcGu9cy9Vyd+q1k3+lr9aXahFApub1fdEytzhxFNRS31d3CSt+7cySQbfD5SM8xWylmYsyOn2l2lPPQn3MTDMlRkMnszHMprvLqfT1EkJkkbQxiWqlp4BtcV13Eiw3nQtm4CuC+WyDJK/1BFifwoofeAme4XF751MX3wJI5wiXVcm7xDLxYEPPWWIFPjMLHIc4xET7MeiHO34n/4kvEDjZnX7YgO7ImC5LQpoOVqYU39InQ5NDhhbeZyYC1EdF7azQj5DJ03T71B43hxIQJ69rg1RlXEibu5pubWvFhZP+kMja0c8r7ga5/26mWvbSt+k3OW8NXRFEZVDo0SjlHgEbGpHo3g26Y3KHgKCd+veZCSgoltBB+MMKq38T/OoE0sg/aTjLGL60tnAoOfJTn6agHLzPdrRVO0TPYl6te4f9RQ4cm1Cqdc/UMsCTz/e+C70y3nHCAgDCYgpj1gZIWEg5deeMvJAGqpHd9JVfjmtMTPbMNzUnzBJzHeBVVFRG96y8v1/5OjdW3a8J3+6EoxrfkIHU0ZTMk55n6UVjGMgOcLdKlVqBXkz07JJHz2eqTR89pS2fh49Qaen/0XpGDw2XED5ppNOUc/hktsrnjPQvkiEUgY/07sp0zr2YE74wU6lByTY3EHY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
