travis:
  secure:
    BINSTAR_TOKEN: Tu+xdXLhe3FGwHNO+NVVQQOu+x31lS+kCMfu9+1gwo4iIOO447yFHvSKR6/hDoW3+kMwropWAXpL3t192OVfAevC5z/1r574I5xsmI6GR3eAh845PKvvwTcQvSkATeYCeCBiAl2/YmdvGjLemvtc4rPmkduKrc1iquqJ/fab6JcOPD8cf6zpA3BtGgyRZC6vROnQjXsX9rx2NwaO22DXTudKc7PfUQfP42OEGtZFrXQzjjT3vcLp9a2SrPH6uFdHr7vcGAQmhoiZqPnrlsrs5fQ4gUwUBtrpdV+8c9cwlmfOdllOPdjntSbjXBw3WuV77skdEZ1rA12E1HnOdgvvhC9h7WqU6mvxmfUwwJELvpfQVuktIG4smTwYRUau7QgOkcRMExwq5ZzG5pGHhu4YGDGE7RdZPqsgBGcFb9S2F0jF7MJW7vg5U0Ph0zH+wNOUCik2AGco7qTW6JOVSq6ThVYgJUEMB/gHlEAbLvLorjz/cg8VCTYxNNOP+Uaxw1g7WAA8WoGVynO6qbmeX/PZL853z3Y3b4mvthJV/QGirpv5jp/20v+GM5lmW7QoUJy7wqs1I+cV5b+UYT1gX5rG1918Fb3LKz55Ssezxh5u86jVhDE2i8zOphuZm1WYv19gCBVhCH2Ukdf0KdX4la7Q2bgx2ruA9XNf1ZXWhO2TC6k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
